---
label: Site Config
hide_body: false
fields:
- name: canonical_url
  label: Canonical URL
  type: text
  hidden: false
  default: ''
  description: The canonical URL to your production site.
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: textarea
  hidden: false
  default: ''
- name: footer
  label: Footer
  type: textarea
  config:
    wysiwyg: true
    schema:
      format: inline_html
  hidden: false
  default: ''
